name: deploy beta.rosenpass.eu

on:
  push:
    branches:
      - beta

permissions:
  contents: read

concurrency:
  group: deploy-beta
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy: true
      server-dir: ${{ vars.FLOKINET_FTP_DIR_BETA }}
    secrets:
      RPLATEX: ${{ secrets.RPLATEX }}
      FLOKINET_FTP_USERNAME: ${{ secrets.FLOKINET_FTP_USERNAME_BETA }}
      FLOKINET_FTP_PASSWORD: ${{ secrets.FLOKINET_FTP_PASSWORD_BETA }}
