name: Update docs
on:
  push:
    branches:
      - main
jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: AliceOrunitia/rosenpass
          path: doc
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mandoc
      - name: Compile docs
        run: |
          cd doc
          for file in *.*
          do
            mandoc -Thtml "$file" > "${file%.*}.html"
          done
          mv *.html ../AliceOrunitia/rosenpass-website/static/docs/
