name: deploy rosenpass.eu

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy: true
      server-dir: ${{ vars.FLOKINET_FTP_DIR }}
    secrets:
      RPLATEX: ${{ secrets.RPLATEX }}
      FLOKINET_FTP_USERNAME: ${{ secrets.FLOKINET_FTP_USERNAME }}
      FLOKINET_FTP_PASSWORD: ${{ secrets.FLOKINET_FTP_PASSWORD }}
