name: Webhook Receiver

on:
  push:
    branches:
      - main

jobs:
  process_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Receive webhook
        run: |
          echo "Webhook received: ${GITHUB_EVENT_NAME}"
          echo "${GITHUB_EVENT_PAYLOAD}"
